### ISSUE TITLE
Is it possible to dynamically determine node size and provide it to vtree?

### ISSUE THREAD

**Issue by filipesilva** [Lodin/react-vtree#16]
Heya 👋 

First of all, sorry if I'm asking a known question, I'm just not too familiar with this library.

I've a tree structure whose nodes can have different heights. I'm not sure if I can know each height easily though. For some nodes I can calculate it just by knowing the content since they are text. But other nodes have things like embed content that can have hard to determine heights.

`react-virtualized` has [CellMeasurer](https://github.com/bvaughn/react-virtualized/blob/master/docs/CellMeasurer.md), which is available for tree structures in https://diogofcunha.github.io/react-virtualized-tree/#/examples/node-measure.

The `resize` function sounds like it should help with this, if I had a way to measure the height of the element directly. `react-window` seems to be working on just-in-time measured content in https://github.com/bvaughn/react-window/issues/6. But it's not very clear to me how could it be applied to the vtree nodes. 

Is there a good way to determine the node height and pass it to the resize function, similar to CellMeasurer?

**Comment by Lodin** [comment]
Hi @filipesilva, thanks for the question. Actually, that's the first time I meet that case, so I don't have the ready answer for you.

However, I have a couple of thoughts about it. The approach is quite simple and usually used for auto-sizing a textarea element. All you need is the `div` element, absolutely positioned and moved out of visibility. Then, during the run of `treeWalker`, you calculate each element's height putting it to that `div` and getting the real height of that element. The requirement is that you need elements to load synchronously. Then you measure the height of the hidden element and put it to the `defaultHeight` of the yielding object in `treeWalker`. And voila: you have all the heights calculated.

The issue is a performance penalty, so, probably, you would need a cache to avoid re-calculating the height of the already measured element because the `treeWalker` runs each time you toggle the tree branch.

If you need asynchronous elements, you may want to use the `resize` function of the tree node. I'm not sure where it should be called; probably, in the `Node` component on mounting.

**Comment by Lodin** [comment]
Hi @filipesilva, thanks for the question. Actually, that's the first time I meet that case, so I don't have the ready answer for you.

However, I have a couple of thoughts about it. The approach is quite simple and usually used for auto-sizing a textarea element. All you need is the `div` element, absolutely positioned and moved out of visibility. Then, during the run of `treeWalker`, you calculate each element's height putting it to that `div` and getting the real height of the element. The requirement is that you need elements to load synchronously. Then you measure the height of the hidden element and put it to the `defaultHeight` of the yielding object in the `treeWalker`. And voila: you have all the heights calculated.

The issue is a performance penalty, so, probably, you would need a cache to avoid re-calculating the height of the already measured element because the `treeWalker` runs each time you toggle the tree branch.

If you need asynchronous elements, you may want to use the `resize` function of the tree node. I'm not sure where it should be called; probably, in the `Node` component on mounting.

**Comment by filipesilva** [comment]
Thanks for the quick reply! I think your suggestion is exactly what https://github.com/bvaughn/react-window/pull/102 (the PR for https://github.com/bvaughn/react-window/issues/6) does. I imagine the most performant way of doing it is to do it asynchronously, so that the initial render isn't blocked.

You mentioned it was a common technique for textareas. Do you know of a library that does it well?

**Comment by Lodin** [comment]
@filipesilva, yeah, probably, that's the only way we have for now. 

> You mentioned it was a common technique for textareas. Do you know of a library that does it well?

Sure. When I studied that topic, I have gone through the Andrey Popp's [`react-textarea-autosize`](https://github.com/andreypopp/react-textarea-autosize). There is a lot of code but the part that is interesting for you is the [`calculateNodeHeight`](https://github.com/andreypopp/react-textarea-autosize/blob/master/src/calculateNodeHeight.js) function.

**Comment by Lodin** [comment]
Ok, I would consider this question as answered. Feel free to reopen if you have something to add!
