### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by aanich-assf** [Lodin/react-vtree#2]
Hi! I like your work a lot and let me preface this by saying this is not a request for the feature to be implemented into the library. My question is - how much time do you think it would take to integrate either a react-specific DND (react-dnd) or regular HTML5 DND with this library?

**Comment by Lodin** [comment]
Hi @aanich-assf! Glad to know that my little library served you well! 

Regarding your question: I don't have very much experience in HTML5 DnD and I still haven't had a chance to work with `react-dnd`, so it's quite hard to say. However, since `react-vtree` is about working with pure data, I suppose it wouldn't take a lot of time to integrate it with DnD. I see it in the following way: you change your data listening to dragging events, re-render the tree using `recomputeTree()`, `update` prop or just regular React update and then get necessary information displayed. 

Also there is [sortable-tree](https://github.com/frontend-collective/react-sortable-tree) that is based on `react-virtualized` as well and has built-in support for DnD.
