### ISSUE TITLE
Deleting a node from tree

### ISSUE THREAD

**Issue by suwigyarathore** [Lodin/react-vtree#55]
I am adding dynamic nodes by modifying the data structure( which is a prop) and adding children at appropriate levels. I enabled async so the tree open state remains fine. Just the children are added dynamically.  So that works fine.
But when I do the same for delete the node is deleted from the data structure which is passed a prop but the tree is not re-rendered with that removed node.

**Comment by suwigyarathore** [comment]
finally managed to fix it

**Comment by spbo** [comment]
> 
> 
> finally managed to fix it

Hi @suwigyarathore! Is there any chance to share me, your code and your fix? I' m trying to add/ remove nodes with useState without success.

**Comment by yen-ranoa** [comment]
Hello @suwigyarathore , same here with @spbo how to delete nodes and refresh the tree with the removed node? thanks, a little help here thaanks

**Comment by alexkatz** [comment]
I ran into a similar issue, and found out what my problem was.

First of all, make sure your `treeWalker` function gets reset to a new instance once you've deleted your node. Any time you add or remove a node (or move a node, for that matter, which can be seen as delete + add), the reference to your `treeWalker` function needs to change for the tree to be re-rendered.

My issue was a tad more nuanced. After moving a node to another parent, I noticed that the original node was lingering in the DOM at its position prior to being moved. I scratched my head for a bit before realizing that this issue was caused by the required `id: string` property within the `data` object that the `treeWalker` function consumes.

I was `toString`ing my nodes' numeric `id` property for this value. Since I was removing and re-adding the node to another part of the tree, this id never left the tree, and therefore I assume was not removed from the DOM. After changing my ids to something like `"${node.id}-${node.parent.id}"`, my issue went away, as the "deleted" node's id was now actually gone by the time the "new" node was added under its new parent.

@spbo  @yen-ranoa no idea if this is relevant to your issues, but I hope it helps!
