### ISSUE TITLE
stable version

### ISSUE THREAD

**Issue by viktor89** [Lodin/react-vtree#6]
This looks exactly like what I need!
What are some of the tasks needed for a stable release of this?

**Comment by Lodin** [comment]
Well, actually, I created it as a stable version because, at that moment, I was the only user of the library, and I wanted to test it in the battle before setting up the stable version. However, I didn't find any error, so, probably, I should just publish the stable version as is.

I think you can use the beta version and then update it to the stable because I'm not going to introduce any breaking changes.

I'm going to leave this issue open until the stable version is released.

**Comment by viktor89** [comment]
Anything you would like added, that I can contribute, let me know :)

**Comment by Lodin** [comment]
Released version `1.0.0`
