### ISSUE TITLE
Setting component state onClick causes the tree to lose focus position during keyboard navigation and go to top of the rendered tree

### ISSUE THREAD

**Issue by amyplin11** [Lodin/react-vtree#94]
This is during keyboard navigation: in my use case, I need to keep track of the "selected" node in state so I can apply specific styles to it - when a node is clicked setState is called.

In this simplified example, I have a state variable called 'test' and am calling setTest in the onClick of the node. If you press 'tab' down the nodes and then press 'enter' and 'tab' again, you'll see that the focus is set to the top of the tree instead of staying in place. 
Example: https://codesandbox.io/s/react-vtree-forked-n8xl7l?file=/src/App.tsx

Using react-dev-tools I see that each Row has a unique key set as expected, so I'm not sure what the issue is, if anyone has any ideas please let me know!

**Comment by paolosimone** [comment]
I think the problem is that the `Node` function is defined inside the `TreePresenter` component, which is re-rendered whenevere `setTest` is called.

The solution should be:
- move `Node` definition outside
- pass the state `{test, setTest}` through the `itemData` prop of the tree and read it from the [treeData prop of the node](https://github.com/Lodin/react-vtree#rowcomponent-component)

Working example: https://codesandbox.io/s/react-vtree-forked-b6ed5c?file=/src/App.tsx

**Comment by amyplin11** [comment]
ah that makes sense, thanks!
